### ISSUE TITLE
2nd Error Report

### ISSUE THREAD

**Issue by Riemann2357** [andreaferretti/commutative-algebra#2]
In Proposition 1.3.11, I think we need to assume that f is surjective, or that the submodules of f(M) are in bijective correspindence with submodules of M containing ker f.

Otherwise two submodules of R can have same inverse image: consider inclusion of Z into Z[i] as a Z-module homomorphism; both the trivial subgroup and the subgroup generated by i have trivial inverse image.

**Comment by andreaferretti** [comment]
Thank you @Riemann2357 , you are right on both accounts (this and the previous issue). Sorry I was a little sloppy. I will add these to a list of errata I plan to eventually release (I have only few for now)

**Comment by Riemann2357** [comment]
Thanks for reply! I tried to read other books such as Atiyah-Macdonald or Eisenbud, but they were not satisfactory, so I searched and found your book. I think I would read your book thoroughly afterwards, and I would write here in case of any other problems. Thanks for writing a good book.
