### ISSUE TITLE
A question regarding book

### ISSUE THREAD

**Issue by Riemann2357** [andreaferretti/commutative-algebra#4]
In the Example 1.4.4 (e), I think the seqeunce is actually split. Therefore I have some questions.

(1) Are we considering the exact sequence of k-modules?
(2) Is the surjective map A->k given by ax+b+(x^2) \mapsto b?
(3) If answers to (1) and (2) are yes, I see no reason for the sequence to be non-split. The map A->k has section k->A, b mapsto b+(x^2). Am I missing something?

**Comment by andreaferretti** [comment]
No, the sequence has to be regarded as a sequence of A-modules. Exact sequences of k-modules (i.e., vector spaces) are always split, because vector spaces admit bases.

In your example, the section you give is k-linear, but not A-linear, hence it does not prove that the sequence splits

**Comment by Riemann2357** [comment]
Thanks. Is the A-module structure on k given by the action x*t = 0 for t in k? If so I can indeed see that the sequence is not split.

**Comment by andreaferretti** [comment]
It is, on the first `k`. The second `k` inherits an action by virtue of being a quotient, and by the way `A` is defined, it turns out that the action is the same.
