### ISSUE TITLE
6th Error

### ISSUE THREAD

**Issue by Riemann2357** [andreaferretti/commutative-algebra#6]
1. In the proof of Theorem 1.5.6, the reasoning for a_i | a_{i+1} is omitted. I think it might be better to mention about it.
2. In Corollary 1.5.7, we have elements a_1, a_2, \cdots, a_k, but the formula is written as A^r\times A/(a_1)\times \cdots\times A/(a_r).
3. In the proof of Theorem 1.5.9, the moves do not preserve the determinant, but the absolute value of the determinant. Exchanging rows or columns may change its sign.

**Comment by andreaferretti** [comment]
1. I think at this point the conclusion is clear - if not, it is a good occasion to fill in all details. Unfortunately, for reason of space, it sometimes happens has to choose the level of detail of a proof, which is not always up to the smallest detail
2. Right, thank you, it should be `A^r \times A / (a_1) \times \cdots \times A / (a_k)`
3. Right
